name: Update News
on:
  schedule:
    - cron: '0 * * * *'  # Se ejecuta cada hora
  workflow_dispatch:     # Permite ejecución manual
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install feedparser beautifulsoup4 requests yfinance
      - name: Run script
        run: python tu_script.py
      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add .
          git commit -m "Automatic news update"
          git push
